import { useState } from "react";
import { PageHeader, EmptyState } from "@/components/ui/Display";
import { Button } from "@/components/ui/Button";
import { TableScroll, Th, Td } from "@/components/ui/Table";
import { Modal } from "@/components/ui/Modal";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { Field, Input, Select } from "@/components/ui/Field";
import { formatDate, formatMoney } from "@/lib/format";
import { useDeleteSale, useRecordSale, useSales, useUpdateSale } from "@/hooks/useSales";
import { useInventoryItems, useItemThumbnails } from "@/hooks/useInventory";
import { useMarketplaceAccounts, usePostingAccounts } from "@/hooks/useAccounts";
import { useItemPostings, usePlatforms } from "@/hooks/usePlatforms";
import { ItemThumbnail } from "@/components/inventory/ItemThumbnail";
import { useAuth } from "@/context/AuthContext";
import { CodeScannerButton } from "@/components/inventory/CodeScannerButton";
import { PublicIdSortSelect } from "@/components/inventory/PublicIdSortSelect";
import { sortByPublicId, type PublicIdSortOrder } from "@/lib/inventorySort";

export function SoldPage() {
  const { profile } = useAuth(); const isAdmin = profile?.role === "admin";
  const { data: sales, isLoading } = useSales(); const [query, setQuery] = useState("");
  const [sortOrder, setSortOrder] = useState<PublicIdSortOrder>("oldest");
  const { data: thumbnails } = useItemThumbnails((sales ?? []).map((s: any) => s.inventory_item_id));
  const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<any>(); const [toUnsell, setToUnsell] = useState<string | null>(null); const unsell = useDeleteSale();
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean); const rows = sortByPublicId((sales ?? []).filter((s: any) => !terms.length || terms.some((term) => [s.inventory_item?.item_name,s.inventory_item?.legacy_public_id,s.inventory_item?.sku].some((value) => value?.toLowerCase().includes(term)))), (sale: any) => sale.inventory_item?.legacy_public_id, sortOrder);
  return <div className="flex flex-col gap-4"><PageHeader title="Sold" subtitle={`${sales?.length ?? 0} sales`} actions={<Button onClick={() => setAdding(true)}>+ Record sale</Button>} /><div className="flex flex-wrap gap-2"><Input type="search" placeholder="Search name, public ID or SKU…" value={query} onChange={(e) => setQuery(e.target.value)} className="max-w-xs" /><CodeScannerButton onDetected={(codes) => setQuery(codes.join(" "))} /><PublicIdSortSelect value={sortOrder} onChange={setSortOrder} /></div>
    {isLoading ? <p className="text-sm text-neutral-400">Loading…</p> : !rows.length ? <EmptyState title="No sales found" /> : <TableScroll><thead><tr><Th>Date</Th><Th>Item</Th><Th>Platform</Th><Th>Account</Th><Th></Th>{isAdmin && <Th right>Price</Th>}</tr></thead><tbody>{rows.map((s: any) => <tr key={s.id}><Td>{formatDate(s.sale_date)}</Td><Td><div className="flex items-center gap-2"><ItemThumbnail src={thumbnails?.get(s.inventory_item_id)} name={s.inventory_item?.item_name ?? "Item"}/><div className="font-medium">{s.inventory_item?.item_name ?? "—"}<div className="text-xs text-neutral-400">{s.inventory_item?.legacy_public_id}</div></div></div></Td><Td>{s.sale_platform ?? "—"}</Td><Td>{s.marketplace_account_id ?? "-"}</Td><Td><Button variant="ghost" onClick={() => setEditing(s)}>Edit</Button><Button variant="ghost" onClick={() => setToUnsell(s.id)}>Unsell</Button></Td>{isAdmin && <Td right>{formatMoney(s.sold_price)}</Td>}</tr>)}</tbody></TableScroll>}
    {adding && <SaleForm onClose={() => setAdding(false)} />}{editing && <SaleForm sale={editing} onClose={() => setEditing(undefined)} />}{toUnsell && <ConfirmDialog open title="Unsell this item" message="This reverses the account and wallet entries and returns the item to inventory." confirmLabel="Unsell" danger onCancel={() => setToUnsell(null)} onConfirm={async () => { await unsell.mutateAsync(toUnsell); setToUnsell(null); }} />}
  </div>;
}

function SaleForm({ sale, onClose }: { sale?: any; onClose: () => void }) {
  const { data: available = [] } = useInventoryItems({ status: "available" }); const { data: platforms = [] } = usePlatforms(); const { data: accounts = [] } = useMarketplaceAccounts(); const { data: postingAccounts = [] } = usePostingAccounts(); const { data: postings = [] } = useItemPostings(available.map((i) => i.id));
  const record = useRecordSale(); const update = useUpdateSale(); const [itemId, setItemId] = useState(sale?.inventory_item_id ?? ""); const [search, setSearch] = useState(""); const [sortOrder, setSortOrder] = useState<PublicIdSortOrder>("oldest"); const [price, setPrice] = useState(sale?.sold_price == null ? "" : String(sale.sold_price)); const [platform, setPlatform] = useState(sale?.sale_platform ?? platforms[0]?.slug ?? "vinted"); const [accountId, setAccountId] = useState(sale?.marketplace_account_id ?? ""); const [date, setDate] = useState(sale?.sale_date ?? new Date().toISOString().slice(0,10)); const [error, setError] = useState<string | null>(null);
  const visible = sortByPublicId(available.filter((i) => { const q = search.toLowerCase(); return !q || [i.item_name,i.legacy_public_id,i.sku].some((v) => v?.toLowerCase().includes(q)); }), (item) => item.legacy_public_id, sortOrder).slice(0,80);
  function choose(id: string) { setItemId(id); const post = postings.find((p) => p.inventory_item_id === id && p.platform_slug === platform && p.status === "posted"); const postAccount = post && postingAccounts.find((a) => a.id === post.posting_account_id); if (postAccount?.marketplace_account_id) setAccountId(postAccount.marketplace_account_id); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(null); if (!itemId) return setError("Choose an item."); try { const input = { inventory_item_id: itemId, sold_price: Number(price) || 0, sale_platform: platform || null, marketplace_account_id: accountId || null, sale_date: date || null }; if (sale) await update.mutateAsync({ id: sale.id, input }); else await record.mutateAsync(input); onClose(); } catch (err) { setError(err instanceof Error ? err.message : "Could not save sale."); } }
  const saleAccounts = accounts.filter((a) => a.platform === platform);
  return <Modal open onClose={onClose} title={sale ? "Edit sale" : "Record a sale"}><form onSubmit={submit} className="flex flex-col gap-4">{!sale && <Field label="Find product"><Input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name, public ID or SKU…" /><div className="mt-2"><PublicIdSortSelect value={sortOrder} onChange={setSortOrder} /></div><div className="mt-2 max-h-40 overflow-auto rounded border border-neutral-200">{visible.map((i) => <button type="button" key={i.id} onClick={() => choose(i.id)} className={`block w-full border-b p-2 text-left text-sm hover:bg-neutral-50 ${itemId === i.id ? "bg-neutral-100" : ""}`}>{[i.legacy_public_id, i.item_name].filter(Boolean).join(" · ")}</button>)}</div>{itemId && <small className="text-neutral-500">Selected: {available.find((i) => i.id === itemId)?.item_name}</small>}</Field>}<Field label="Sold for"><Input type="number" step="0.01" required value={price} onChange={(e) => setPrice(e.target.value)} /></Field><Field label="Platform"><Select value={platform} onChange={(e) => { setPlatform(e.target.value); setAccountId(""); }}>{platforms.map((p) => <option key={p.slug} value={p.slug}>{p.name}</option>)}<option value="cash">Cash</option><option value="other">Other</option></Select></Field><Field label="Account"><Select value={accountId} onChange={(e) => setAccountId(e.target.value)}><option value="">- (not posted / no account)</option>{saleAccounts.map((a) => <option key={a.id} value={a.id}>{a.label}</option>)}</Select></Field><Field label="Date"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={record.isPending || update.isPending}>{record.isPending || update.isPending ? "Saving…" : "Save"}</Button></div></form></Modal>;
}
