-- Reset a banned marketplace account's posting records within the same
-- transaction. Match both explicit links and legacy numbered accounts.
create or replace function public.reset_postings_for_banned_account()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.banned and not old.banned then
    update public.item_postings ip
       set status = 'needs_posting', posting_account_id = null
     where ip.posting_account_id in (
       select pa.id
         from public.posting_accounts pa
        where pa.marketplace_account_id = new.id
           or (new.posting_account_number is not null
               and pa.platform = new.platform
               and pa.account_number = new.posting_account_number)
     );
  end if;
  return new;
end $$;
drop trigger if exists trg_reset_postings_for_banned_account on public.marketplace_accounts;
create trigger trg_reset_postings_for_banned_account
  after update of banned on public.marketplace_accounts
  for each row execute function public.reset_postings_for_banned_account();

-- Bulk posting updates run as one database transaction, so a single Undo
-- restores the whole search result set.
create or replace function public.set_item_postings_bulk(
  p_inventory_item_ids uuid[], p_platform_slug text, p_status text, p_posting_account_id uuid
) returns integer language plpgsql set search_path = public as $$
declare affected integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_status not in ('needs_posting', 'skipped', 'posted') then raise exception 'Invalid posting status'; end if;
  if not exists (select 1 from public.platforms where slug = p_platform_slug and is_active) then raise exception 'Platform is not active'; end if;
  if p_status = 'posted' and (p_posting_account_id is null or not exists (
    select 1 from public.posting_accounts pa
     where pa.id = p_posting_account_id and pa.platform = p_platform_slug
       and not exists (
         select 1 from public.marketplace_accounts ma
          where ma.banned and (ma.id = pa.marketplace_account_id
            or (ma.platform = pa.platform and ma.posting_account_number = pa.account_number))
       )
  )) then raise exception 'Choose a posting account for this platform'; end if;

  insert into public.item_postings (inventory_item_id, platform_slug, status, posting_account_id)
  select distinct item_id, p_platform_slug, p_status,
         case when p_status = 'posted' then p_posting_account_id else null end
    from unnest(p_inventory_item_ids) as selected(item_id)
   where item_id is not null
  on conflict (inventory_item_id, platform_slug) do update
    set status = excluded.status, posting_account_id = excluded.posting_account_id;
  get diagnostics affected = row_count;
  return affected;
end $$;
grant execute on function public.set_item_postings_bulk(uuid[], text, text, uuid) to authenticated;

-- Keep the latest user changes as reversible transaction groups. This
-- includes posting, closet, chapter, and app changes that were not captured
-- by the original Undo triggers.
alter table public.undo_events add column if not exists transaction_id bigint;
alter table public.undo_events add column if not exists event_order bigint generated by default as identity;
create index if not exists idx_undo_events_user_recent on public.undo_events(user_id, event_order desc)
  where undone_at is null;

create or replace function public.capture_undo()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if current_setting('project26.undo_replay', true) = 'on' or auth.uid() is null then
    return coalesce(new, old);
  end if;
  -- Sale and account balance transactions are derived from their parent
  -- records and must be reversed by those parent actions.
  if tg_table_name = 'wallet_transactions' then
    if coalesce(new.related_sale_id, old.related_sale_id) is not null
       or coalesce(new.reason, old.reason) not in ('Wallet add', 'Wallet take', 'Set balance') then
      return coalesce(new, old);
    end if;
  end if;
  insert into public.undo_events(user_id, table_name, operation, row_before, row_after, transaction_id)
  values(auth.uid(), tg_table_name, tg_op,
         case when tg_op <> 'INSERT' then to_jsonb(old) end,
         case when tg_op <> 'DELETE' then to_jsonb(new) end,
         txid_current());
  return coalesce(new, old);
end $$;

drop trigger if exists trg_undo_inventory_items on public.inventory_items;
create trigger trg_undo_inventory_items after insert or update or delete on public.inventory_items for each row execute function public.capture_undo();
drop trigger if exists trg_undo_packages on public.packages;
create trigger trg_undo_packages after insert or update or delete on public.packages for each row execute function public.capture_undo();
drop trigger if exists trg_undo_marketplace_accounts on public.marketplace_accounts;
create trigger trg_undo_marketplace_accounts after insert or update or delete on public.marketplace_accounts for each row execute function public.capture_undo();
drop trigger if exists trg_undo_sales on public.sales;
create trigger trg_undo_sales after insert or update or delete on public.sales for each row execute function public.capture_undo();
drop trigger if exists trg_undo_trades on public.trades;
create trigger trg_undo_trades after insert or update or delete on public.trades for each row execute function public.capture_undo();
drop trigger if exists trg_undo_closet_items on public.closet_items;
create trigger trg_undo_closet_items after insert or update or delete on public.closet_items for each row execute function public.capture_undo();
drop trigger if exists trg_undo_chapters on public.chapters;
create trigger trg_undo_chapters after insert or update or delete on public.chapters for each row execute function public.capture_undo();
drop trigger if exists trg_undo_closet_sections on public.closet_sections;
create trigger trg_undo_closet_sections after insert or update or delete on public.closet_sections for each row execute function public.capture_undo();
drop trigger if exists trg_undo_posting_accounts on public.posting_accounts;
create trigger trg_undo_posting_accounts after insert or update or delete on public.posting_accounts for each row execute function public.capture_undo();
drop trigger if exists trg_undo_item_postings on public.item_postings;
create trigger trg_undo_item_postings after insert or update or delete on public.item_postings for each row execute function public.capture_undo();
drop trigger if exists trg_undo_platforms on public.platforms;
create trigger trg_undo_platforms after insert or update or delete on public.platforms for each row execute function public.capture_undo();
drop trigger if exists trg_undo_wallet_transactions on public.wallet_transactions;
create trigger trg_undo_wallet_transactions after insert on public.wallet_transactions for each row execute function public.capture_undo();

-- Undoing a manual wallet adjustment deletes its transaction. Reverse the
-- balance delta on deletion too, while sales continue to add compensating rows.
create or replace function public.apply_wallet_transaction()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    update public.wallet_balances set balance = balance + new.amount, updated_at = now() where bucket = new.bucket;
    return new;
  end if;
  update public.wallet_balances set balance = balance - old.amount, updated_at = now() where bucket = old.bucket;
  return old;
end $$;
drop trigger if exists trg_apply_wallet_transaction on public.wallet_transactions;
create trigger trg_apply_wallet_transaction after insert or delete on public.wallet_transactions
  for each row execute function public.apply_wallet_transaction();

-- Undo all rows written by the most recent transaction, up to ten recent
-- transactions remain available in the UI. Replaying skips new undo records.
create or replace function public.undo_latest_action()
returns text language plpgsql security definer set search_path = public as $$
declare
  latest_event public.undo_events;
  e public.undo_events;
  target uuid;
  assignments text;
begin
  select * into latest_event
    from public.undo_events
   where user_id = auth.uid() and undone_at is null and expires_at > now()
   order by event_order desc limit 1 for update;
  if not found then raise exception 'Nothing to undo'; end if;
  perform set_config('project26.undo_replay', 'on', true);

  for e in
    select * from public.undo_events
     where user_id = auth.uid() and undone_at is null and expires_at > now()
       and ((latest_event.transaction_id is not null and transaction_id = latest_event.transaction_id)
         or (latest_event.transaction_id is null and id = latest_event.id))
     order by event_order desc for update
  loop
    if e.table_name not in ('inventory_items','packages','marketplace_accounts','sales','trades','closet_items','chapters','closet_sections','posting_accounts','item_postings','platforms','wallet_transactions') then
      raise exception 'This change cannot be undone safely';
    end if;
    target := coalesce((e.row_after->>'id')::uuid, (e.row_before->>'id')::uuid);
    if e.operation = 'INSERT' then
      execute format('delete from public.%I where id = $1', e.table_name) using target;
    elsif e.operation = 'DELETE' then
      execute format('insert into public.%I select * from jsonb_populate_record(null::public.%I, $1)', e.table_name, e.table_name) using e.row_before;
    else
      select string_agg(format('%I = (jsonb_populate_record(null::public.%I, $2)).%I', column_name, e.table_name, column_name), ', ')
        into assignments
        from information_schema.columns
       where table_schema = 'public' and table_name = e.table_name and column_name <> 'id';
      execute format('update public.%I set %s where id = $1', e.table_name, assignments) using target, e.row_before;
    end if;
    update public.undo_events set undone_at = now() where id = e.id;
  end loop;
  return latest_event.table_name || ' transaction';
end $$;
grant execute on function public.undo_latest_action() to authenticated;

create or replace function public.undo_available_count()
returns integer language sql security definer set search_path = public as $$
  select least(count(distinct coalesce('tx:' || transaction_id::text, 'event:' || id::text)), 10)::integer
    from public.undo_events
   where user_id = auth.uid() and undone_at is null and expires_at > now();
$$;
grant execute on function public.undo_available_count() to authenticated;
